import { StyleSheet } from 'react-native';


export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    },
  textLoginCadastro: {
    fontSize: 65,
    textAlign: 'center',
    color: 'white',
  },
  container1: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  containerAjuste: {
    paddingRight: 10,
    paddingLeft: 10,
    paddingTop: 70,
  },
  containerCheckbox: {
    borderRadius: 10,
    marginBottom:10,
    justifyContent: 'center',
  },
  container2: {
    display: 'flex',
    flexDirection: 'row',
    padding: 20,
    justifyContent: 'center',
  },
  containerInputPesquisa: {
    display: 'flex',
    flexDirection: 'row',
  },
  containerCaracteristicasReceita: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  containerCabecalho: {
    display: 'flex',
    flexDirection: 'row',
    jus: 'flex-end',
    marginBottom: 20,
    padding: 0,
    justifyContent: 'space-between',
  },
  containerReceita: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 5,
    paddingLeft: 20,
    paddingRight: 20,
    justifyContent: 'center',
    borderRadius: 10,
    borderWidth: 1,
  },
  containerUsuario: {
    height: 80,
    display: 'flex',
    flexDirection: 'row',
    marginTop: 20,
    marginBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
    paddingBottom: 5,
    paddingTop: 5,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
  },
  containerConfigs: {
    height: '81%',
    marginTop: 10,
    marginBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
    paddingBottom: 5,
    paddingTop: 5,
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
  },
  containerCores: {
    display: 'flex',
    flexDirection: 'row',
    paddingLeft: 10,
    paddingRight: 10,
    paddingBottom: 5,
    paddingTop: 5,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  containerAddReceita: {
    padding: 5,
    borderRadius: 10,
    borderWidth: 1,
  },
  
  separacaoBotaoUsuario: {
    justifyContent: 'space-between',
  },
  quad: {
    height: 40,
    width: 40,
    marginRight: 20,
  },
  textDadosUsuario: {
    fontSize: 20,
    color: 'black',
    textAlign: 'center',
    background: 'white',
    borderRadius: 5,
    height: 35,
  },
  textLoginECadastro: {
    fontSize: 40,
    color: 'white',
    textAlign: 'center',
  },
  textAvaliacaoCheckbox: {
    height: 20,
    width: 20,
    color: 'white',
    borderRadius: 10,
    marginBottom:10,
  },
  textCadastrese: {
    fontSize: 17,
    color: 'white',
    textAlign: 'center',
    padding: 0,
  },
  imgInicial: {
    borderRadius: 5,
    width: '20%',
    height: '50%',
    resizeMode: 'stretch',
    marginTop: '12%',
  },
  imgReceita: {
    borderRadius: 5,
    width: '100%',
    height: 220,
    resizeMode: 'stretch',
  },
  imgUser: {
    borderRadius: 5,
    width: '20%',
    height: '100%',
    resizeMode: 'stretch',
  },
  imgLogin: {
    borderRadius: 5,
    width: '100%',
    height: '50%',
    resizeMode: 'stretch',
    marginTop: '12%',
  },
  imgCadastro: {
    borderRadius: 5,
    width: '90%',
    height: '30%',
    resizeMode: 'stretch',
    marginTop: '12%',
  },
  imgVoltar: {
    borderRadius: 5,
    width: '10%',
    height: 30,
    resizeMode: 'stretch',
    marginTop: '12%',
  },
  imgVoltarPesquisa: {
    borderRadius: 5,
    width: '10%',
    height: 30,
    resizeMode: 'stretch',
    marginTop: '1%',
    marginBottom: '1%',
  },
  imgLupa: {
    borderRadius: 5,
    width: '100%',
    height: 30,
    resizeMode: 'stretch',
  },
  imgPreview: {
    borderRadius: 5,
    marginTop: 10,
    width: 30,
    height: 30,
    resizeMode: 'stretch',
  },
  viewImgPreview: {
    alignItems: 'center',
  },
  textMenuInicial: {
    fontSize: 20,
    color: 'white',
    marginTop: 3,
    borderRadius: 5,
    height: 35,
  },
  textNomeUsuario: {
    fontSize: 20,
    color: 'white',
  },
  textDescInicial: {
    fontSize: 10,
    color: 'white',
    marginTop: 0,
    borderRadius: 5,
    height: 35,
  },
  textItensInicialAcima: {
    fontSize: 17,
    color: 'white',
    textAlign: 'center',
  },
  textUsuarioSair: {
    fontSize: 17,
    color: '#f00',
    textAlign: 'center',
  },
  textTituloInicial: {
    fontSize: 20,
    color: 'white',
    textAlign: 'center',
    marginBottom: 10,
  },
  textItensConfig: {
    fontSize: 14,
    color: 'white',
    textAlign: 'justify',
    marginBottom: 10,
  },
  textAddReceita: {
    fontSize: 28,
    color: 'white',
    marginTop: 20,
    marginBottom: 20,
    textAlign: 'center',
  },
  textTituloReceita: {
    fontSize: 28,
    color: 'white',
    marginTop: 20,
    marginBottom: 20,
    textAlign: 'center',
  },
  textAddReceitaItens: {
    fontSize: 17,
    color: 'white',
    marginTop: 5,
    textAlign: '',
  },
  textSwitches: {
    fontSize: 12,
    color: 'white',
    marginTop: 1,
    alignItems: 'center',
  },
  textReceitaItens: {
    fontSize: 13,
    color: 'white',
    marginTop: 5,
    textAlign: 'justify',
  },
  textReceitaItens2: {
    fontSize: 13,
    color: 'white',
    marginTop: 5,
    paddingRight: 15,
    textAlign: 'justify',
  },
  textInputAddReceitaDescricao: {
    fontSize: 15,
    color: 'black',
    marginTop: 5,
    marginBottom: 10,
    height: 100,
    borderRadius: 5,
    backgroundColor: 'white',
  },
  textInputAddReceitaNome: {
    fontSize: 15,
    color: 'black',
    marginTop: 5,
    marginBottom: 10,
    height: 40,
    borderRadius: 5,
    backgroundColor: 'white',
  },
  textInputPesquisa: {
    fontSize: 15,
    width: '90%',
    color: 'black',
    marginTop: 5,
    marginBottom: 10,
    height: 40,
    borderRadius: 5,
    backgroundColor: 'white',
  },
  pressablePesquisa: {
    fontSize: 15,
    width: '10%',
    color: 'black',
    marginTop: 5,
    marginBottom: 10,
    height: 30,
    borderRadius: 5,
  },
});
